apiVersion: v1
kind: Service
metadata:
  namespace: sat-organization
  labels:
    name: employee-service    
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8082
  selector:
    app: employee-service
  type: LoadBalancer
